Autoscale
amitnayak1505/Deploy_VPC_using_Terraform pull request #12
Opened 2022-09-06 18:12 UTC by amitnayak1505

2022-09-06 18:59 UTC, vladimirmukhin requested changes

2022-09-06 18:59 UTC, vladimirmukhin commented on asg.tf
> +  image_id        = var.ami
Please use aws ami data source instead of variable

2022-09-06 18:59 UTC, vladimirmukhin commented on asg.tf
> +  user_data       = file("userdata1.sh")
the `userdata1.sh` is missing in git

2022-09-06 18:59 UTC, vladimirmukhin commented on asg.tf
> +  desired_capacity     = var.asg_count
No need to parametrize this setting

2022-09-06 18:59 UTC, vladimirmukhin commented on asg.tf
> +  vpc_zone_identifier  = [aws_subnet.public[count.index].id]
This will not work

2022-09-07 16:48 UTC, amitnayak1505 commented on asg.tf
> +  user_data       = file("userdata1.sh")
added to the git

2022-09-07 17:18 UTC, amitnayak1505 commented on asg.tf
> +  desired_capacity     = var.asg_count
Made the changes

2022-09-07 17:18 UTC, amitnayak1505 commented on asg.tf
> +  vpc_zone_identifier  = [aws_subnet.public[count.index].id]
updated

2022-09-07 18:41 UTC, vladimirmukhin approved these changes

2022-09-12 10:32 UTC, merged